---
title: How many otolith growth increments are necessary to reliably estimate growth models and population age-structure?
author:
  - name: Daniel Ricard
    email: Daniel.Ricard@dfo-mpo.gc.ca
    affiliation: Fisheries and Oceans Canada
    corresponding: Daniel.Ricard@dfo-mpo.gc.ca
  - name: Alex Hanke
    email: Alex.Hanke@dfo-mpo.gc.ca
    affiliation: Fisheries and Oceans Canada
    corresponding: Daniel.Ricard@dfo-mpo.gc.ca
  - name: Lisa Ailloud
    email: bob@example.com
    affiliation: Southeast Fisheries Science Center
  - name: Cóilín Minto
    email: bob@example.com
    affiliation: Galway Mayo Institute of Technology 
  - name: Olaf Jensen
    email: bob@example.com
    affiliation: University of Wisconsin
abstract: |
  Abstract goes here.
  
author_summary: |
  Author summary goes here.

bibliography: mybibfile.bib
output: rticles::plos_article
# plos.csl can be download and used locally
csl: http://www.zotero.org/styles/plos
---

_Text based on plos sample manuscript, see <https://journals.plos.org/ploscompbiol/s/latex>_

# Introduction

Measuring length of captured individuals is easier and faster than obtaining detailed information through dissection. Information about fisheries activities often consists in length frequency samples. A subset of individuals measured are subjected to more detailed sampling, including the removal of otoliths.

It is important to determine the appropriate number of individuals to sample during a survey, in order to ascertain that the goals of the sampling are fulfilled. In the case of measuring fish and collecting otoliths under typical sampling protocols, the number of otoliths collected will scale with the abundance of a species, given that it follows a wide enough length distribution. The challenge is to then determine the number of otoliths that have to be aged in order to obtain reliable estimates of the age-structure of the population of interest.

Under many survey protocols, otoliths are removed  from captured individuals following a length-stratified sampling design. A typical protocol would be to obtain 2 otoliths for each cm length bin.

Identifying growth annuli on a digital image and obtaining cartesian coordinates for the annual points along a chosen axis provides length proxies for each year in the life of an individual. The age-length pairs derived from growth increments are not independent of each other and are pseudo-replicates. 

A practical question is how many otoliths should be aged in order to obtain reliable and unbiased estimates of growth and of age structure.


# Methods

## Simulation of an age-structured population

An age-structured population dynamics model was used to simulate observations of fish length and age. The simulation approach generates observations mimicking those obtained during survey activities and provide both a reference of the "true state" of the population and the observations from that population.

The goal of the simulated observations is to maintain the uncertainty known to exist in natural systems and to harness contemporary computational power to implement robust analyses. 

## Growth increments of flatfish in the southern Gulf of St. Lawrence

Digital images of otolihs collected from commercial fishing activities and scientific trawl surveys in the southern Gulf of St. Lawrence were obtained using Leica S9i microscope. The images were sharpened and enhanced using filters applied using ImageMagick before being uploaded to the SmartDots software for image annotation. Trained fish agers annotated the digital images to obtain the annual growth increment measurements required to perform individual fish growth back-calculations. 

## Estimation of von Bertalanffy model parameters



## Age-length keys and catch-at-age matrices

The hybrid forward-inverse age-length key described in @10.1093/icesjms/fsz072 is used to generate catch-at-age matrices from length samples and age-length keys.


Catch-at-age matrices used as inputs to age-structured stock assessment models are used to compute removals in the population and also as tuning indices for model fitting. 

The "true" yearly age composition is available from the simulated age-structured population. The age composition estimated from age-length keys can be visually compared to the known age composition using residuals plots. Additionally, a single measure of concordance is the Relative Mean Square Error (RMSE), which reports the overall agreement between two catch-at-age matrices. 

# Results

## Simulations

## American Plaice otolith growth increments

# Discussion


# References {#references .unnumbered}
